### ISSUE TITLE
When loading page you get no title while the application renders

### ISSUE THREAD

**Issue by robclancy** [adopted-ember-addons/ember-page-title#116]
This flicker of the default `index.html` title to the set title using the helper has annoyed me for a while now. I hacked in `node_modules` to test out a way to fix it. I don't know how you would want to do it but removing the title completely from the DOM when the application has just started (can load from API, etc, then have to render) is a bad solution due to having no title for what can be a long time depending on bootstrapping.

I commented out the `instance-initializer` that removed the title and added instead the following in the `title` helper...

```js
let removedInitialTitle = false;

function updateTitle(tokens) {
  if (! removedInitialTitle) {
    let titles = document.getElementsByTagName('title');
    for (let i = 0; i < titles.length; i++) {
      let title = titles[i];
      title.parentNode.removeChild(title);
    }

    removedInitialTitle = true;
  }

  set(this, 'title', tokens.toString());
}
```

This means you can use the `index.html` `<title>` as a default that will stay until this addon knows of a title to include. Not sure if you need `fastboot` stuff here. I'm not going to use this code, just wait for changes to the addon unless you decide you don't want to do it.

**Comment by tim-evans** [comment]
This seems like a fine solution to me 👍 

A PR for this would be welcome

**Comment by knownasilya** [comment]
I think we do this now.
