### ISSUE TITLE
title is not a helper

### ISSUE THREAD

**Issue by OlmoDalco** [adopted-ember-addons/ember-page-title#123]
After installing ember-page-title and including the {{title "title"}} helper in the template, ember still returns with the following error: **Compile Error: title is not a helper**

**Comment by tim-evans** [comment]
Humm. This is transformed by using a HBS transform. You could use `{{page-title}}` as an alternative

**Comment by tim-evans** [comment]
See https://github.com/tim-evans/ember-page-title/blob/latest/index.js#L9 for the code that makes this happen

**Comment by knownasilya** [comment]
As far as I know using `{{title}}` errors when using https://github.com/rwjblue/ember-angle-bracket-invocation-polyfill in your project.

**Comment by tim-evans** [comment]
@knownasilya there's a hbs precompile step that helps ember disambiguate between `{{title}}` the variable and `{{title}}` the helper. It essentially rewrites all `{{title}}` helpers (which have arguments) into `{{page-title}}` helpers.

**Comment by tim-evans** [comment]
https://github.com/tim-evans/ember-page-title/blob/latest/lib/plugins/translate-helper-name.js

**Comment by knownasilya** [comment]
Yeah, looks like the invocation polyfill is broken for helpers of all kinds since v1.1.0 (v1.0.2 works).

**Comment by raido** [comment]
i think can be closed as we don't support `{{title}}` syntax no longer  - https://github.com/adopted-ember-addons/ember-page-title/pull/176
