### ISSUE TITLE
Can't set own title

### ISSUE THREAD

**Issue by erzzo** [adopted-ember-addons/ember-page-title#126]
Hi,
I followed the instructions and tried some things, but I can't get it to work.
When my app is loading my default title from index.html will be shown. When the app loads, it is changing like here described:
Title on / route: http://localhost:4200/
Contact route: http://localhost:4200/contact

It switches the title but I can't insert my own title like in the guide.

- ember cli 2.16.2
- using pod structure (I've tried to create /app/head/template.hbs with no success, like here described https://github.com/tim-evans/ember-page-title/issues/37)
- without fastboot

What's wrong?

**Comment by MelSumner** [comment]
Closing this issue, as it looks like guidance was provided. @erzzo please let us know if you have any more issues. Thank you!
