### ISSUE TITLE
Replace Ember.merge with Ember.assign

### ISSUE THREAD

**Issue by Windvis** [adopted-ember-addons/ember-page-title#136]
Ember v3.6 has deprecated [Ember.merge](https://emberjs.com/deprecations/v3.x/#toc_ember-polyfills-deprecate-merge).

**Comment by Windvis** [comment]
Oh, it looks like there is already a pull request for this: https://github.com/adopted-ember-addons/ember-page-title/pull/133

**Comment by acorncom** [comment]
This issue can be closed now
