### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by knownasilya** [adopted-ember-addons/ember-page-title#138]
@tim-evans I'm looking to get a new release out. Have there been any maintainers interested? If no, I'd be happy to temporarily handle that (need npm perms, my user is `knownasilya` on npm).

**Comment by tim-evans** [comment]
No maintainers yet 🤷‍♂️

**Comment by tim-evans** [comment]
I’ve added you under npm @knownasilya

**Comment by knownasilya** [comment]
v5.0.1 Released
