### ISSUE TITLE
RFC: remove template transpilation step

### ISSUE THREAD

**Issue by knownasilya** [adopted-ember-addons/ember-page-title#140]
Currently `{{title ..}}` is transpiled into `{{page-title ..}}` when you build your app. This seems like mainly a reaction to the fact that some people had used `{{title}}` elsewhere and had errors.

With the addition of `this` and `@`, the ambiguity is a lot smaller. At the same time, all apps that use this addon are currently using `{{page-title}}` since it's transpiled. I recommend releasing a new major version that transitions the syntax to `{{page-title}}` and removes the build step. We would also provide a codemod to rename all `{{title ..}}` to `{{page-title ..}}` (already have this code, just need to package it).

This transition could start in v5.0.0 by changing the docs to `{{page-title}}` and later deprecating `{{title ..}}`, although I'm not sure how we'd do that, maybe with a tweak to the AST transformation like `{{page-title _logDeprecation=true}}`.

**Comment by efx** [comment]
Implementing this would better support applications using embroider. In order to get page title working with embroider you need to use `{{page-title}}` directly, as the AST transformation does not seem to run.

**Comment by raido** [comment]
@knownasilya this seems outdated as well due to removal of AST transform.
