### ISSUE TITLE
Setting prepend to false doesn't reflect in the title

### ISSUE THREAD

**Issue by shadyvd** [adopted-ember-addons/ember-page-title#142]
The app/services/page-title-list checks (config.pageTitle && config.pageTitle[key]), and sets the value of defaultPrepend, etc.

If config.pageTitle.prepend === false, this will never get set because the check will always return false.

The check needs to be modified to (config.pageTitle && config.pageTitle[key] !== null)

**Comment by cah-briangantzler** [comment]
I have upgraded the 5.0 series and the prepend is now true by default, but I cant set it back in the config due to this outstanding issue. 

Any update here?

**Comment by knownasilya** [comment]
Should be fixed in the next major version, give master a try.
