### ISSUE TITLE
document {{head-layout}} more clearly

### ISSUE THREAD

**Issue by burritoIand** [adopted-ember-addons/ember-page-title#144]
addon is not working in ember 3.4.1 with version `"ember-page-title": "5.0.1"`

**Comment by esantelises** [comment]
@erichonkanen i was running into same issue was because i didn't add `{{head-layout}}` to application.hbs take a look at [upgrading notes for 3.x to 4.x](https://github.com/adopted-ember-addons/ember-page-title#upgrading-notes-for-3x-to-4x)

**Comment by erichonkanen** [comment]
@esantelises wow missed that! thank you!

**Comment by deanmarano** [comment]
It would be helpful if this was more prominent in the installation. I added this add-on to my app (not upgrading) so I didn't think to look at the upgrading instructions.

**Comment by lucasmerat** [comment]
+1 to @deanmarano ... just spent an hour or so fiddling with the addon as it wasn't working correctly. This would be good to have front-and-center in installation docs

**Comment by knownasilya** [comment]
@lucasmerat will make sure to update.
