### ISSUE TITLE
fix currentRouteName deprecation in the dummy app

### ISSUE THREAD

**Issue by efx** [adopted-ember-addons/ember-page-title#148]
The dummy [application.hbs](https://github.com/adopted-ember-addons/ember-page-title/blob/latest/tests/dummy/app/templates/application.hbs#L2) references `currentRouteName`. This has been [deprecated](https://deprecations.emberjs.com/v3.x/#toc_application-controller-router-properties). We should fix this to avoid the console noise as demonstrated below: 
https://travis-ci.org/adopted-ember-addons/ember-page-title/jobs/544795758#L523

You can also see this locally when testing.

**Comment by raido** [comment]
@knownasilya this seems to have PR merged some time ago and can be closed.
