### ISSUE TITLE
Error: Cannot find serialized cursor for `in-element`

### ISSUE THREAD

**Issue by st-h** [adopted-ember-addons/ember-page-title#155]
I installed this add-on as described in the [docs](https://adopted-ember-addons.github.io/ember-page-title/) and did not see any title. After I came here, I noticed that I would need to remove any title meta tag from my `index.html` page (due to my use of fastboot) and add the `{{head-layout}}` tag. `head.hbs` has automatically been created. ember version is 3.14.3

After adding `{{head-layout}}` my app no longer boots and throws this error:
```
Error: Cannot find serialized cursor for `in-element` runtime.js:5823
    getMarker runtime.js:5823
    __pushRemoteElement runtime.js:5827
    pushRemoteElement runtime.js:3447
    <anonymous> runtime.js:977
    evaluate runtime.js:73
    evaluateSyscall runtime.js:3295
    evaluateInner runtime.js:3241
    evaluateOuter runtime.js:3233
    next runtime.js:5299
    next runtime.js:5335
    Ember 6
        render
        runInTransaction
        runInTransaction
        _renderRoots
        _renderRootsTransaction
        _revalidate
    invokeWithOnError backburner.js:347
    flush backburner.js:229
    flush backburner.js:426
    _end backburner.js:960
    end backburner.js:710
    _runExpiredTimers backburner.js:1097
    _runExpiredTimers self-hosted:867
```

Has anyone else seen something similar?

The only thing I could find is [this issue](https://github.com/emberjs/ember.js/issues/18020), which is not much of help. However, it seems quite related, as the only workaround I could find so far is to disable fastboot.

Unfortunately I can not provide a reproducer right now.

**Comment by knownasilya** [comment]
@st-h can you test with Ember v3.17?

**Comment by st-h** [comment]
@knownasilya quick test looks good. Will try to test more asap
