### ISSUE TITLE
Release 5.2.4

### ISSUE THREAD

**Issue by alexlafroscia** [adopted-ember-addons/ember-page-title#163]
It seems like `5.2.4` was tagged on GitHub but has not yet made it to NPM.

Could someone with the appropriate permissions do that?

(Technically I can myself, but would rather someone more familiar with this project gives the OK first)

**Comment by knownasilya** [comment]
Will do, although it's only fixing tests, no user facing changes.

**Comment by raido** [comment]
Closing this in favour of v6.x which was recently released. 

@knownasilya if we really want to keep NPM registry in sync with tags then we either publish it or delete the tag 🤔 .
