### ISSUE TITLE
Deprecation warning with Ember 3.20

### ISSUE THREAD

**Issue by boris-petrov** [adopted-ember-addons/ember-page-title#164]
Starting with Ember 3.20, the following warning appears in the console:

```
DEPRECATION: The use of the private `{{-in-element}}` is deprecated, please refactor to the public `{{in-element}}`. ('ember-cli-head/templates/components/head-layout.hbs' @ L1:C0)  [deprecation id: glimmer.private-in-element]
```

This is because `ember-page-title` uses `ember-cli-head` `0.4.0` which uses the private `-in-element`. Version `1.0.0` has this issue resolved so a simple bump of the version should suffice to fix this.

**Comment by knownasilya** [comment]
Should be resolved by https://github.com/adopted-ember-addons/ember-page-title/pull/162

**Comment by knownasilya** [comment]
Will be released this week

**Comment by knownasilya** [comment]
Resolved with https://github.com/adopted-ember-addons/ember-page-title/pull/168
