### ISSUE TITLE
remove dependency on ember-cli-head

### ISSUE THREAD

**Issue by MelSumner** [adopted-ember-addons/ember-page-title#167]
TODO: Change `ember-page-title` to remove the `ember-cli-head` requirement (for both SSR and in browser)
Teams will have to add the ember-cli-head addon if they want the functionality from both.

This will unblock the [related RFC](https://github.com/emberjs/rfcs/pull/645)

We'll need to create a new release and do a major version bump. 

Notes: 
After this is finished, update RFC 645 to add both ember-page-title and ember-cli-head as dev dependencies of apps.

**Comment by knownasilya** [comment]
Any tips on how to approach this? Manually update the title?

**Comment by buschtoens** [comment]
What about fastboot? 🤔

**Comment by MelSumner** [comment]
@knownasilya that's a good question- I'm going to try to look at it today, but maybe @rwjblue has some advice if he can get to it before me.

**Comment by rwjblue** [comment]
We don't need ember-cli-head in order to support FastBoot. The scenarios that we need to care about are:

* client side render (no rehydration)
* client side render (rehydrating prior)
* server side render

Both of the client side renders can be accommodated by manipulating `document.title` directly.

The server side render can be manipulated by setting `.title` on the internal/private `SimpleDOM` document. For example, like this:

```js
let document = owner.lookup('service:-document');
document.title = 'whatever';
```

**Comment by rwjblue** [comment]
For more context, the `service:-document` thing is passed through [here](https://github.com/emberjs/ember.js/blob/ee8a894980fad6664a26ba78c8d949891abf811b/packages/%40ember/application/instance.js#L306-L308), and it is _basically_ either going to be the normal global `document` instance **or** the FastBoot created `SimpleDOM.Document` (see [here for some inline docs](https://github.com/emberjs/ember.js/blob/ee8a894980fad6664a26ba78c8d949891abf811b/packages/%40ember/application/instance.js#L430-L455) and [where that `BootOptions` is built in FastBoot](https://github.com/ember-fastboot/fastboot/blob/429eb1d1c3d9353f3085196e71cfde416f154cba/src/ember-app.js#L355-L371)).
