### ISSUE TITLE
"You attempted to update length on Class" on ember canary

### ISSUE THREAD

**Issue by mydea** [adopted-ember-addons/ember-page-title#172]
All my tests for an addon started failing on canary recently. After doing some digging, it seems it is caused by this addon.

Basically, if I remove the `{{title}}` declaration in my index route template:

```hbs
{{head-layout}}
{{title 'my addon'}}
```

Everything works again. If there is at least one `{{titlte}}` anywhere, I get:

Error: Assertion Failed: You attempted to update `length` on `Class`, but it had already been used previously in the same computation.  Attempting to update a value after using it in a computation can cause logical errors, infinite revalidation bugs, and performance issues, and is not supported.

**Comment by knownasilya** [comment]
This should be resolved with #168 or related prs.

**Comment by boris-petrov** [comment]
@knownasilya - Ember 3.22 is out and this error prevents us from upgrading to it. Is a new version of `ember-page-title` going to be released to address this?

**Comment by knownasilya** [comment]
Looking to see if a release can happen tonight. Will update you here.

**Comment by knownasilya** [comment]
v6 should be out now.

**Comment by boris-petrov** [comment]
@knownasilya - thank you for the immediate response! Works like a charm, thank you!
