### ISSUE TITLE
property in path "headData" could not be found

### ISSUE THREAD

**Issue by mazondo** [adopted-ember-addons/ember-page-title#36]
Uncaught Error: Property set failed: object in path "headData" could not be found or was destroyed.

Hit it after updating to newest version.

line: page-title.js:9

Seems fastboot related, but I'm unfamiliar with it.  Any ideas?

**Comment by knownasilya** [comment]
@mazondo did you resolve your issue? It appears like #24 helped?

**Comment by mazondo** [comment]
Yep, all good.
