### ISSUE TITLE
Loading substates breaks titles in history

### ISSUE THREAD

**Issue by janmisek** [adopted-ember-addons/ember-page-title#56]
History does not contain title of nested route when loading substates are used for the route.

*To reproduce*:
- Create application route with title "Application"
- Create route post with title "Post", model hook should delay something like 100ms
- Create route user with title "User", model hook should delay something like 100ms
- Create loading substate for application route 

Switch post and title few times, using link-to component. History (right click on browser back-button) contains records as "Application | " instead of "Application | Post" and "Application | User"

**Comment by tim-evans** [comment]
Hmm. I'm not sure how to fix this completely.

I recently added some changes to prevent changes when there are loading substates: https://github.com/tim-evans/ember-page-title/blob/master/addon/helpers/page-title.js#L34, which may have changed this behavior. Is this new or existing behavior?

**Comment by janmisek** [comment]
>  is this new or existing behavior

I am not sure, this is first time I am using the addon and its new app.

**Comment by tim-evans** [comment]
I'll try to test this on other browsers to see if behavior varies between them. I think this is dependent on figuring out when a browser takes a snapshot of the page title for history purposes

**Comment by janmisek** [comment]
I tried already in Firefox 50 and chrome 53 - same behaviour. I also migrated today to ember 2.11.1 - same behaviour. I am switching to ember-concurrency now and leaving loading substates. It works properly without them. 

Btw: I would suspect something with browser history management by Ember because even I am setting title like 5 seconds later after model was loaded and template rendered history works properly without loading substates.

**Comment by byrnedo** [comment]
Also getting this, is there any kind of workaround?

**Comment by tim-evans** [comment]
I'm not sure, since I'm not very aware of this. Sorry, @byrnedo

**Comment by byrnedo** [comment]
Actually, nevermind, could have been the ember-cli build going wonky, when I did a production build it worked fine :)

**Comment by tim-evans** [comment]
Super!

**Comment by knownasilya** [comment]
Closing since this is a bit old.
