### ISSUE TITLE
Support use as a `dependency` of an addon

### ISSUE THREAD

**Issue by camskene** [adopted-ember-addons/ember-page-title#95]
We have an internal addon which is used by a number of applications. I wanted to be able to specify `ember-page-title` as  dependency of that addon and then use the `{{title}}` helper from within the apps. Possible?

**Comment by tim-evans** [comment]
I think so! You can add it in the ember-cli section in package.json I think.

**Comment by camskene** [comment]
I tried adding to `devDependencies` and then to `dependencies` in our internal addon with no luck. The consuming app errors with 'Compile Error: title is not a helper'.

**Comment by tim-evans** [comment]
Ahh, that's because this uses a htmlbars-ast-plugin at build time. I may need some help getting that plugin to run for all dependents.

**Comment by tim-evans** [comment]
(See https://github.com/tim-evans/ember-page-title/blob/master/index.js)

**Comment by raido** [comment]
@knownasilya I think this can be closed as AST transform has been removed.

**Comment by knownasilya** [comment]
Good catch
